version: "3"
services:

  web:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      CELERY_BROKER_URL: "amqp://guest:guest@rabbitmq:5672"
      CELERY_RESULT_BACKEND: "amqp://guest:guest@rabbitmq:5672"
    restart: always
    ports:
     - "5000:80"
    depends_on:
      - rabbitmq

  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    environment:
      CELERY_BROKER_URL: "amqp://guest:guest@rabbitmq:5672"
      CELERY_RESULT_BACKEND: "amqp://guest:guest@rabbitmq:5672"
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3
    ports:
        - "5673:5672"